// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpw4mRbco2poiPVnEGogO015qkbNX1THc',
    appId: '1:894251245466:web:ddc00c3f451aa1cb592423',
    messagingSenderId: '894251245466',
    projectId: 'scrapuncle-452708',
    authDomain: 'scrapuncle-452708.firebaseapp.com',
    storageBucket: 'scrapuncle-452708.firebasestorage.app',
    measurementId: 'G-4M2V2SQLFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAosIjIIM_3BtnZtKXFvZi7xSfd5LVVAVA',
    appId: '1:894251245466:android:83a828d2b38fb558592423',
    messagingSenderId: '894251245466',
    projectId: 'scrapuncle-452708',
    storageBucket: 'scrapuncle-452708.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC08i2_UOl_svgUma2zRJIyjMLxhOSdx4g',
    appId: '1:894251245466:ios:85b6ea0540271a33592423',
    messagingSenderId: '894251245466',
    projectId: 'scrapuncle-452708',
    storageBucket: 'scrapuncle-452708.firebasestorage.app',
    iosClientId: '894251245466-ua07im5qf9n3lk99ka9jsa7qb5325lss.apps.googleusercontent.com',
    iosBundleId: 'com.example.scrapuncle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC08i2_UOl_svgUma2zRJIyjMLxhOSdx4g',
    appId: '1:894251245466:ios:85b6ea0540271a33592423',
    messagingSenderId: '894251245466',
    projectId: 'scrapuncle-452708',
    storageBucket: 'scrapuncle-452708.firebasestorage.app',
    iosClientId: '894251245466-ua07im5qf9n3lk99ka9jsa7qb5325lss.apps.googleusercontent.com',
    iosBundleId: 'com.example.scrapuncle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpw4mRbco2poiPVnEGogO015qkbNX1THc',
    appId: '1:894251245466:web:b8fdd231dd7ffde9592423',
    messagingSenderId: '894251245466',
    projectId: 'scrapuncle-452708',
    authDomain: 'scrapuncle-452708.firebaseapp.com',
    storageBucket: 'scrapuncle-452708.firebasestorage.app',
    measurementId: 'G-4HJT864YYL',
  );
}
