// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3TjI-BLQHUNaqrVG0YQoFiyta5rhMcVk',
    appId: '1:161775820792:web:e059979c15a6b0870e800d',
    messagingSenderId: '161775820792',
    projectId: 'scrapuncle-b4fac',
    authDomain: 'scrapuncle-b4fac.firebaseapp.com',
    storageBucket: 'scrapuncle-b4fac.firebasestorage.app',
    measurementId: 'G-CYVYCLWLKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7CPNn917-GJrfPO5dI1r5-GOtUW02fEY',
    appId: '1:161775820792:android:14498379119d25e00e800d',
    messagingSenderId: '161775820792',
    projectId: 'scrapuncle-b4fac',
    storageBucket: 'scrapuncle-b4fac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV-FVyQlgyl7Jc--WHn6bOcJb8hcdJZks',
    appId: '1:161775820792:ios:631e2247223d51910e800d',
    messagingSenderId: '161775820792',
    projectId: 'scrapuncle-b4fac',
    storageBucket: 'scrapuncle-b4fac.firebasestorage.app',
    iosBundleId: 'com.example.scrapuncle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV-FVyQlgyl7Jc--WHn6bOcJb8hcdJZks',
    appId: '1:161775820792:ios:631e2247223d51910e800d',
    messagingSenderId: '161775820792',
    projectId: 'scrapuncle-b4fac',
    storageBucket: 'scrapuncle-b4fac.firebasestorage.app',
    iosBundleId: 'com.example.scrapuncle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3TjI-BLQHUNaqrVG0YQoFiyta5rhMcVk',
    appId: '1:161775820792:web:76826ebd8f7501f10e800d',
    messagingSenderId: '161775820792',
    projectId: 'scrapuncle-b4fac',
    authDomain: 'scrapuncle-b4fac.firebaseapp.com',
    storageBucket: 'scrapuncle-b4fac.firebasestorage.app',
    measurementId: 'G-6BELL98TTG',
  );
}
